# Relógio
- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: "BIDIRECTIONAL"

- topic_name: "/world/panda_world/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: "BIDIRECTIONAL"

- topic_name: /panda/ft_sensor_finger1
  ros_type_name: geometry_msgs/msg/Wrench
  gz_type_name: gz.msgs.Wrench
  direction: "BIDIRECTIONAL"

- topic_name: /panda/ft_sensor_finger2
  ros_type_name: geometry_msgs/msg/Wrench
  gz_type_name: gz.msgs.Wrench
  direction: "BIDIRECTIONAL"

# Câmeras RGB
- topic_name: "/depth_camera_1"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "BIDIRECTIONAL"

- topic_name: "/depth_camera_2"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "BIDIRECTIONAL"

# Câmeras Info
- topic_name: "/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "BIDIRECTIONAL"

# Nuvem de pontos
- topic_name: "/depth_camera_1/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: "BIDIRECTIONAL"

- topic_name: "/depth_camera_2/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: "BIDIRECTIONAL"

# Pose GUI
- topic_name: "/gui/camera/pose"
  ros_type_name: "geometry_msgs/msg/Pose"
  gz_type_name: "gz.msgs.Pose"
  direction: "BIDIRECTIONAL"

# Poses do mundo
- topic_name: "/world/panda_world/pose/info"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: "BIDIRECTIONAL"

- topic_name: "/world/panda_world/dynamic_pose/info"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: "BIDIRECTIONAL"

# Estado do mundo
- topic_name: "/world/panda_world/state"
  ros_type_name: "gazebo_msgs/msg/WorldState"
  gz_type_name: "gz.msgs.WorldStatistics"
  direction: "BIDIRECTIONAL"

- topic_name: "/world/panda_world/stats"
  ros_type_name: "gazebo_msgs/msg/WorldState"
  gz_type_name: "gz.msgs.WorldStatistics"
  direction: "BIDIRECTIONAL"

- topic_name: "/model/panda/joint/panda_joint1/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "BIDIRECTIONAL"

- topic_name: "/model/panda/joint/panda_joint2/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "BIDIRECTIONAL"

- topic_name: "/model/panda/joint/panda_joint3/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "BIDIRECTIONAL"

- topic_name: "/model/panda/joint/panda_joint4/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "BIDIRECTIONAL"

- topic_name: "/model/panda/joint/panda_joint5/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "BIDIRECTIONAL"

- topic_name: "/model/panda/joint/panda_joint6/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "BIDIRECTIONAL"

- topic_name: "/model/panda/joint/panda_joint7/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "BIDIRECTIONAL"

- topic_name: "/model/panda/joint/panda_finger_joint1/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "BIDIRECTIONAL"

- topic_name: "/model/panda/joint/panda_finger_joint2/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "BIDIRECTIONAL"
