authorized_labels:
  - firecabinet_
  - box
  - trashcan
  - case_
  - eletricheater_
  - drum_
  - cardbox_
  - box_
  - conveyor_
  - storage_
  - greenbox_
  - redbox_
  - blackbox_
  - bluebox_
  - wall_

unauthorized_labels:
  - camera