# PARÂMETROS GERAIS

/**:
  ros__parameters:
    use_sim_time: true

# SERVER NODE

server_node_with_llms:
  ros__parameters:
    use_sim_time: true
    yaml_file: ""          # Preenchido pelo launch
    subtrees_path: ""      # Preenchido pelo launch
    database_path: ""      # Preenchido pelo launch

# COMPOSABLE NODES
storage_node:
  ros__parameters:
    use_sim_time: true
    label_to_storage_yaml_file: ""   # Preenchido pelo launch
    storage_poses_yaml_file: ""      # Preenchido pelo launch

reachability_node:
  ros__parameters:
    use_sim_time: true
    path_resolution: 0.05
    security_distance: 0.2

ik_validator_node:
  ros__parameters:
    use_sim_time: true
    group_name: "panda_arm"

cloud_box_filter:
  ros__parameters:
    use_sim_time: true
    debug_filtered_points: false

bridge_to_inference:
  ros__parameters:
    use_sim_time: true
    server_host: "localhost"
    server_port: 5000
    score_threshold: 0.15
    max_grasps: 50
    target_frame: "world"

world_state_node:
  ros__parameters:
    use_sim_time: true
    database_path: ""      # Preenchido pelo launch


# NÓS SEPARADOS

bridge_to_phi_3_5:
  ros__parameters:
    use_sim_time: true
    model_name: "phi35_leve"

a_star:
  ros__parameters:
    use_sim_time: true
    path_resolution: 0.05
    iterations_before_verification: 20

controller:
  ros__parameters:
    use_sim_time: true
    path_resolution: 0.05
    iterations_before_verification: 20

obstacle_graph_with_occupancy_grid:
  ros__parameters:
    use_sim_time: true
    map_yaml_file: ""      # Preenchido pelo launch
    map_image_file: ""     # Preenchido pelo launch
    max_security_distance: 0.45
    obstacle_graph_resolution: 0.05

manipulation:
  ros__parameters:
    use_sim_time: true
    yaml_file: ""          # Preenchido pelo launch

add_collision_objects:
  ros__parameters:
    use_sim_time: true
    yaml_file: ""          # Preenchido pelo launch

move_group:
  ros__parameters:
    use_sim_time: true
    num_planning_attempts: 200