sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /mapped_object
    max_range: 5.0
    octomap_resolution: 0.0075
    point_subsample: 1
    padding_offset: 0.05
    padding_scale: 1.0
    max_update_rate: 5.0
    filtered_cloud_topic: filtered_cloud
